apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.nodeFeatureDiscovery }}
  namespace: openshift-nfd
  labels:
    app: {{ .Values.app }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: nfd
  source: redhat-operators
  sourceNamespace: openshift-marketplace