apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    app.kubernetes.io/component: {{ .Values.app }}
    app.kubernetes.io/instance: {{ .Values.app }}
    app.kubernetes.io/name: {{ .Values.app }}
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel