apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    app.kubernetes.io/part-of: argocd
data:
  ELASTICSEARCH_HOST: {{ .Values.data.elasticsearchHost }}
  ELASTICSEARCH_USERNAME: {{ .Values.data.elasticsearchUsername }}
  ELASTICSEARCH_PASSWORD: {{ .Values.data.elasticsearchPassword }}
  ELASTICSEARCH_DOCUMENT_INDEX: {{ .Values.data.elasticsearchDocumentIndex }}
  ELASTICSEARCH_TELEGRAM_INDEX: {{ .Values.data.elasticsearchTelegramIndex }}
  TENSORFLOW_HUB_EMBEDDING_MODEL_URL: {{ .Values.data.tensorflowHubEmbeddingModelUrl }}
  GOOGLE_API_KEY: {{ .Values.data.googleApiKey }}
  GOOGLE_MODEL: {{ .Values.data.googleModel }}
  GOOGLE_MODEL_MAX_TOKENS: {{ .Values.data.googleModelMaxTokens }}
  TELEGRAM_TOKEN: {{ .Values.data.telegramToken }}
  MISTRAL_INFERENCE_SERVICE: {{ .Values.data.mistralInferenceService }}