kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: image-registry.openshift-image-registry.svc:5000/{{ .Values.app }}/{{ .Values.app }}:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ .Values.app }}