apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: {{ .Values.app }}
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: {{ .Values.app }}
      namespace: {{ .Values.app }}