apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mistral.modelName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.mistral.storage.size }}