apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mistral.modelName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http-{{ .Values.mistral.modelName }}
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ .Values.mistral.modelName }}
  sessionAffinity: None
  type: ClusterIP