apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    app.kubernetes.io/part-of: argocd
data:
  PVC_NAME: pvc-pipelines
  PVC_STORAGE_CLASS: gp3-csi
  PVC_ACCESS_MODES: ReadWriteOnce
  PVC_SIZE: 5Gi
  S3_SERVICE_NAME: s3
  S3_ENDPOINT_URL: http://demo-app-minio.demo-app-minio.svc.cluster.local:9000
  S3_ACCESS_KEY_ID: minio
  S3_SECRET_ACCESS_KEY: minio123
  S3_REGION: my-region
  S3_BUCKET: telegram-pipelines
  ELASTICSEARCH_HOST: https://demo-app-elasticsearch-es-default.demo-app-elasticsearch.svc.cluster.local:9200
  ELASTICSEARCH_USERNAME: elastic
  ELASTICSEARCH_PASSWORD: elasticsearch_password
  ELASTICSEARCH_DOCUMENT_INDEX: document
  TENSORFLOW_HUB_EMBEDDING_MODEL_URL: https://www.kaggle.com/models/google/universal-sentence-encoder/TensorFlow2/multilingual-large/2
  KUBEFLOW_HOST: http://ds-pipeline-dspa.demo-app-telegram-pipeline.svc.cluster.local:8888
