apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  podSelector:
    matchLabels:
      app: ds-pipeline-dspa
      component: data-science-pipelines
  ingress:
    - ports:
        - protocol: TCP
          port: 8443
        - protocol: TCP
          port: 8888
        - protocol: TCP
          port: 8887
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.app }}
  policyTypes:
    - Ingress
