kind: CheCluster
apiVersion: org.eclipse.che/v2
metadata:
  name: {{ .Values.openshiftDevSpaces.name }}
  namespace: {{ .Values.openshiftDevSpaces.namespace }}
spec:
  components: {}
  containerRegistry: {}
  devEnvironments: {}
  gitServices: {}
  networking: {}
